# Generated by Django 4.1.7 on 2023-03-30 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='venue',
        ),
        migrations.AddField(
            model_name='venue',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='core.photo'),
        ),
    ]
