# Generated by Django 4.1.7 on 2023-03-30 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_photo_venue_venue_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='venue_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.venue'),
        ),
    ]
