# Generated by Django 4.1.7 on 2023-03-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_venue_id_photo_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
