# Generated by Django 4.1.7 on 2023-03-30 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_venue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='venues', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
