# Generated by Django 4.1.6 on 2023-04-04 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_venue_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='core.photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='core.venue'),
        ),
    ]
