# Generated by Django 4.1.6 on 2023-04-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_venue_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='core.photo'),
        ),
    ]
