# Generated by Django 4.1.6 on 2023-04-04 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_photo_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.venue'),
        ),
    ]
