# Generated by Django 4.1.6 on 2023-04-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_venue_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='photo',
        ),
    ]
